all:
	g++ -g  topologicalsort.cpp  -std=c++11 -o etoposort
	g++ -g  dfs.cpp  -std=c++11 -o edfs
	g++ -g  ucc.cpp  -std=c++11 -o eucc
	g++ -g  shortestpath.cpp  -std=c++11 -o eshortestparth
	g++ -g  bfs.cpp  -std=c++11 -o ebfs
