all:
	g++ -g  determiniticselection.cpp  -std=c++11 -o edselect
	g++ -g  adjacenlist.cpp  -std=c++11 -o eadj
	g++ -g  quicksort.cpp  -std=c++11 -o equicksort
	g++ -g  inversions.cpp  -std=c++11 -o einversions
	g++ -g  mergesort.cpp  -std=c++11 -o emergesort
	g++ -g  karatsuba.cpp  -std=c++11 -o ekaratsuba
